### ISSUE TITLE
replace $enable-rounded sass variable with individual classes 

### ISSUE THREAD

**Issue by alee** [comses/comses.net#363]
consider removing the `$enable-rounded: false;` in `_variables.scss` and instead override specific elements that need squareness to have no border-radius 

otherwise this appears to prevent all border-radius from badges buttons etc (needs further testing)

**Comment by sgfost** [comment]
bit of an ancient issue but where would we want sharp corners/rounded corners? Just about everything is squared off due to `$enable-rounded`. I think a lot of things tend to look nicer with the small border radius that bootstrap seems to default to but that's awfully subjective. Maybe smooth out button/badges and keep containers and such sharp?

**Comment by alee** [comment]
I think the general sentiment was to support more finely grained / flexible UI designs instead of a one-size-fits-all approach that this variable setting was causing.

Will this still be an issue with the new Vue 3 build + bootstrap 5 PR you're working on though?

**Comment by sgfost** [comment]
How I'm handling the styles now is refactoring the existing stylesheets, which is how I ran into it. It still does the same thing in bootstrap 5.  Ultimately it doesn't really matter too much, besides picking the default we'll use more to avoid tons of explicit overrides
