### ISSUE TITLE
Platform Independent

### ISSUE THREAD

**Issue by MarcoAJanssen** [comses/comses.net#432]
When we upload models we ask for Operating System and Platform Independent is one of the options. The next question is "Platform". Here we refer to two meaning of the word platform, and we should correct this to avoid confusion.

**Comment by alee** [comment]
Good point. How about replacing "Platform Independent" with "Operating System Independent"?

We might also consider renaming the "Platform" concept in our application to something like "Software Framework" since it feels like a mis-used term. Platforms in CS / Software Engineering are a broad concept that [include software frameworks](https://en.wikipedia.org/wiki/Computing_platform) but can also encompass hardware and operating system environments.

Generally speaking I think we are always envisioning the software environment when considering the semi-controlled vocabularies for "Platform".

**Comment by MarcoAJanssen** [comment]
Yes, it might be good to the term Operating System Independent, and for the other platform, use something like Software Framework (perhaps with an example, e.g. NetLogo, Repast, MATLAB, etc).

**Comment by alee** [comment]
Deployed to comses.net
